# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PrakDemo_1
                                 A QGIS plugin
 PrakDemo_1
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-10-20
        copyright            : (C) 2022 by RGBO-01-19 by RTU MIREA
        email                : lkj@kg.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PrakDemo_1 class from file PrakDemo_1.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .PrakDemo_1 import PrakDemo_1
    return PrakDemo_1(iface)
